### ISSUE TITLE
[Readme instructions] Your OpenSSL implementation does not include the RIPEMD160 algorithm

### ISSUE THREAD

**Issue by Rqnsom** [runziggurat/xrpl#123]
After running this step, the issue was encountered:
```
kmnt23@kmnt23-desktop:~/Workspace/xrpl$ python3 tools/account_info.py
Traceback (most recent call last):
  File "/home/kmnt23/Workspace/xrpl/tools/account_info.py", line 5, in <module>
    from xrpl.clients import JsonRpcClient
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/__init__.py", line 2, in <module>
    from xrpl import account, clients, core, ledger, models, transaction, utils, wallet
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/account/__init__.py", line 2, in <module>
    from xrpl.account.main import (
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/account/main.py", line 6, in <module>
    from xrpl.asyncio.account import main
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/__init__.py", line 2, in <module>
    from xrpl.asyncio import account, clients, ledger, transaction, wallet
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/account/__init__.py", line 2, in <module>
    from xrpl.asyncio.account.main import (
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/account/main.py", line 5, in <module>
    from xrpl.asyncio.clients import Client, XRPLRequestFailureException
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/clients/__init__.py", line 2, in <module>
    from xrpl.asyncio.clients.async_json_rpc_client import AsyncJsonRpcClient
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/clients/async_json_rpc_client.py", line 2, in <module>
    from xrpl.asyncio.clients.async_client import AsyncClient
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/clients/async_client.py", line 4, in <module>
    from xrpl.asyncio.clients.client import Client
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/asyncio/clients/client.py", line 6, in <module>
    from xrpl.models.requests.request import Request
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/__init__.py", line 2, in <module>
    from xrpl.models import amounts, currencies, requests, transactions
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/requests/__init__.py", line 34, in <module>
    from xrpl.models.requests.sign import Sign
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/requests/sign.py", line 26, in <module>
    from xrpl.models.transactions.transaction import Transaction
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/transactions/__init__.py", line 6, in <module>
    from xrpl.models.transactions.account_delete import AccountDelete
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/transactions/account_delete.py", line 7, in <module>
    from xrpl.models.transactions.transaction import Transaction
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/models/transactions/transaction.py", line 10, in <module>
    from xrpl.core.binarycodec import encode
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/core/__init__.py", line 2, in <module>
    from xrpl.core import addresscodec, binarycodec, keypairs
  File "/home/kmnt23/.local/lib/python3.10/site-packages/xrpl/core/keypairs/__init__.py", line 16, in <module>
    assert (
AssertionError: Your OpenSSL implementation does not include the RIPEMD160 algorithm,
    which is required by XRPL
```
I had to apply this [solution](https://stackoverflow.com/questions/69922525/python-3-9-8-hashlib-and-ripemd160/72509045#72509045) to make this step work on Mint 2.1

Maybe Readme.md could be updated.

**Comment by aphelionz** [comment]
which README does this belong in, ours?

**Comment by zeapoz** [comment]
Yeah, I'd say so. I could file a quick PR for it soonish.
